//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Book.Module.BusinessObjects.book_main
{

    [DefaultProperty("id")]
    public partial class Bills : DevExpress.Persistent.BaseImpl.BaseObject
    {
        short fid;
        public short id
        {
            get { return fid; }
            set { SetPropertyValue<short>(nameof(id), ref fid, value); }
        }
        Customers fcustomer_id;
        [Association(@"BillsReferencesCustomers")]
        public Customers customer_id
        {
            get { return fcustomer_id; }
            set { SetPropertyValue<Customers>(nameof(customer_id), ref fcustomer_id, value); }
        }
        Employees femployee_id;
        [Association(@"BillsReferencesEmployees")]
        public Employees employee_id
        {
            get { return femployee_id; }
            set { SetPropertyValue<Employees>(nameof(employee_id), ref femployee_id, value); }
        }
        DateTime foccur_date;
        public DateTime occur_date
        {
            get { return foccur_date; }
            set { SetPropertyValue<DateTime>(nameof(occur_date), ref foccur_date, value); }
        }
        short fstatus;
        public short status
        {
            get { return fstatus; }
            set { SetPropertyValue<short>(nameof(status), ref fstatus, value); }
        }
        string fnote;
        public string note
        {
            get { return fnote; }
            set { SetPropertyValue<string>(nameof(note), ref fnote, value); }
        }
        double ftotal_money;
        public double total_money
        {
            get { return ftotal_money; }
            set { SetPropertyValue<double>(nameof(total_money), ref ftotal_money, value); }
        }
        DateTime fcreated_at;
        public DateTime created_at
        {
            get { return fcreated_at; }
            set { SetPropertyValue<DateTime>(nameof(created_at), ref fcreated_at, value); }
        }
        DateTime fupdated_at;
        public DateTime updated_at
        {
            get { return fupdated_at; }
            set { SetPropertyValue<DateTime>(nameof(updated_at), ref fupdated_at, value); }
        }
        [Association(@"Debt_ReportsReferencesBills"), Aggregated]
        public XPCollection<Debt_Reports> Debt_Reportss { get { return GetCollection<Debt_Reports>(nameof(Debt_Reportss)); } }
        [Association(@"Bill_DetailsReferencesBills"), Aggregated]
        public XPCollection<Bill_Details> Bill_Detailss { get { return GetCollection<Bill_Details>(nameof(Bill_Detailss)); } }
    }

}
