//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Book.Module.BusinessObjects.book_main
{

    [DefaultProperty("id")]
    public partial class Bill_Details : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fid;
        public string id
        {
            get { return fid; }
            set { SetPropertyValue<string>(nameof(id), ref fid, value); }
        }
        Bills fbill_id;
        [Association(@"Bill_DetailsReferencesBills")]
        public Bills bill_id
        {
            get { return fbill_id; }
            set { SetPropertyValue<Bills>(nameof(bill_id), ref fbill_id, value); }
        }
        Products fproduct_id;
        [Association(@"Bill_DetailsReferencesProducts")]
        public Products product_id
        {
            get { return fproduct_id; }
            set { SetPropertyValue<Products>(nameof(product_id), ref fproduct_id, value); }
        }
        double funit_price;
        public double unit_price
        {
            get { return funit_price; }
            set { SetPropertyValue<double>(nameof(unit_price), ref funit_price, value); }
        }
        short fquantity;
        public short quantity
        {
            get { return fquantity; }
            set { SetPropertyValue<short>(nameof(quantity), ref fquantity, value); }
        }
        double ftotal_money;
        public double total_money
        {
            get { return ftotal_money; }
            set { SetPropertyValue<double>(nameof(total_money), ref ftotal_money, value); }
        }
    }

}
