//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Book.Module.BusinessObjects.book_main
{

    [DefaultProperty("id")]
    public partial class Customers : DevExpress.Persistent.BaseImpl.BaseObject
    {
        short fid;
        public short id
        {
            get { return fid; }
            set { SetPropertyValue<short>(nameof(id), ref fid, value); }
        }
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        decimal fphone;
        public decimal phone
        {
            get { return fphone; }
            set { SetPropertyValue<decimal>(nameof(phone), ref fphone, value); }
        }
        string faddress;
        public string address
        {
            get { return faddress; }
            set { SetPropertyValue<string>(nameof(address), ref faddress, value); }
        }
        short floyalty_points;
        public short loyalty_points
        {
            get { return floyalty_points; }
            set { SetPropertyValue<short>(nameof(loyalty_points), ref floyalty_points, value); }
        }
        DateTime fcreate_at;
        public DateTime create_at
        {
            get { return fcreate_at; }
            set { SetPropertyValue<DateTime>(nameof(create_at), ref fcreate_at, value); }
        }
        DateTime fupdate_at;
        public DateTime update_at
        {
            get { return fupdate_at; }
            set { SetPropertyValue<DateTime>(nameof(update_at), ref fupdate_at, value); }
        }
        [Association(@"BillsReferencesCustomers"), Aggregated]
        public XPCollection<Bills> BillsCollection { get { return GetCollection<Bills>(nameof(BillsCollection)); } }
        [Association(@"Debt_ReportsReferencesCustomers"), Aggregated]
        public XPCollection<Debt_Reports> Debt_Reportss { get { return GetCollection<Debt_Reports>(nameof(Debt_Reportss)); } }
    }

}
