//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Book.Module.BusinessObjects.book_main
{

    [DefaultProperty("id")]
    public partial class Debt_Reports : DevExpress.Persistent.BaseImpl.BaseObject
    {
        short fid;
        public short id
        {
            get { return fid; }
            set { SetPropertyValue<short>(nameof(id), ref fid, value); }
        }
        Bills fbill_id;
        [Association(@"Debt_ReportsReferencesBills")]
        public Bills bill_id
        {
            get { return fbill_id; }
            set { SetPropertyValue<Bills>(nameof(bill_id), ref fbill_id, value); }
        }
        Customers fcustomer_id;
        [Association(@"Debt_ReportsReferencesCustomers")]
        public Customers customer_id
        {
            get { return fcustomer_id; }
            set { SetPropertyValue<Customers>(nameof(customer_id), ref fcustomer_id, value); }
        }
        Suppliers fsupplier_id;
        [Association(@"Debt_ReportsReferencesSuppliers")]
        public Suppliers supplier_id
        {
            get { return fsupplier_id; }
            set { SetPropertyValue<Suppliers>(nameof(supplier_id), ref fsupplier_id, value); }
        }
        Purchases fpurchases_id;
        [Association(@"Debt_ReportsReferencesPurchases")]
        public Purchases purchases_id
        {
            get { return fpurchases_id; }
            set { SetPropertyValue<Purchases>(nameof(purchases_id), ref fpurchases_id, value); }
        }
        string ftype;
        public string type
        {
            get { return ftype; }
            set { SetPropertyValue<string>(nameof(type), ref ftype, value); }
        }
        DateTime foccur_date;
        public DateTime occur_date
        {
            get { return foccur_date; }
            set { SetPropertyValue<DateTime>(nameof(occur_date), ref foccur_date, value); }
        }
        DateTime fdue_date;
        public DateTime due_date
        {
            get { return fdue_date; }
            set { SetPropertyValue<DateTime>(nameof(due_date), ref fdue_date, value); }
        }
        short fstatus;
        public short status
        {
            get { return fstatus; }
            set { SetPropertyValue<short>(nameof(status), ref fstatus, value); }
        }
        short fpayment_type;
        public short payment_type
        {
            get { return fpayment_type; }
            set { SetPropertyValue<short>(nameof(payment_type), ref fpayment_type, value); }
        }
        string fnote;
        public string note
        {
            get { return fnote; }
            set { SetPropertyValue<string>(nameof(note), ref fnote, value); }
        }
        double fpaid_amount;
        public double paid_amount
        {
            get { return fpaid_amount; }
            set { SetPropertyValue<double>(nameof(paid_amount), ref fpaid_amount, value); }
        }
        double ftotal_money;
        public double total_money
        {
            get { return ftotal_money; }
            set { SetPropertyValue<double>(nameof(total_money), ref ftotal_money, value); }
        }
        DateTime fcreate_at;
        public DateTime create_at
        {
            get { return fcreate_at; }
            set { SetPropertyValue<DateTime>(nameof(create_at), ref fcreate_at, value); }
        }
        DateTime fupdate_at;
        public DateTime update_at
        {
            get { return fupdate_at; }
            set { SetPropertyValue<DateTime>(nameof(update_at), ref fupdate_at, value); }
        }
    }

}
