//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Book.Module.BusinessObjects.book_main
{

    [DefaultProperty("id")]
    public partial class Product_Categories : DevExpress.Persistent.BaseImpl.BaseObject
    {
        short fid;
        [DevExpress.Persistent.Validation.RuleUniqueValue]
        public short id
        {
            get { return fid; }
            set { SetPropertyValue<short>(nameof(id), ref fid, value); }
        }
        Products fproduct_id;
        [Association(@"Product_CategoriesReferencesProducts")]
        public Products product_id
        {
            get { return fproduct_id; }
            set { SetPropertyValue<Products>(nameof(product_id), ref fproduct_id, value); }
        }
        Categories fcategory_id;
        [Association(@"Product_CategoriesReferencesCategories")]
        public Categories category_id
        {
            get { return fcategory_id; }
            set { SetPropertyValue<Categories>(nameof(category_id), ref fcategory_id, value); }
        }
    }

}
