//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Book.Module.BusinessObjects.book_main
{

    [DefaultProperty("id")]
    public partial class Products : DevExpress.Persistent.BaseImpl.BaseObject
    {
        short fid;
        [DevExpress.Persistent.Validation.RuleUniqueValue]
        public short id
        {
            get { return fid; }
            set { SetPropertyValue<short>(nameof(id), ref fid, value); }
        }
        string fname;
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>(nameof(name), ref fname, value); }
        }
        string fauthor;
        public string author
        {
            get { return fauthor; }
            set { SetPropertyValue<string>(nameof(author), ref fauthor, value); }
        }
        double funit_price;
        public double unit_price
        {
            get { return funit_price; }
            set { SetPropertyValue<double>(nameof(unit_price), ref funit_price, value); }
        }
        double funit_cost;
        public double unit_cost
        {
            get { return funit_cost; }
            set { SetPropertyValue<double>(nameof(unit_cost), ref funit_cost, value); }
        }
        string fpuslisher;
        public string puslisher
        {
            get { return fpuslisher; }
            set { SetPropertyValue<string>(nameof(puslisher), ref fpuslisher, value); }
        }
        string fimage_url;
        public string image_url
        {
            get { return fimage_url; }
            set { SetPropertyValue<string>(nameof(image_url), ref fimage_url, value); }
        }
        string fdescr;
        public string descr
        {
            get { return fdescr; }
            set { SetPropertyValue<string>(nameof(descr), ref fdescr, value); }
        }
        DateTime fpublish_date;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime publish_date
        {
            get { return fpublish_date; }
            set { SetPropertyValue<DateTime>(nameof(publish_date), ref fpublish_date, value); }
        }
        double fdiscount_percentage;
        public double discount_percentage
        {
            get { return fdiscount_percentage; }
            set { SetPropertyValue<double>(nameof(discount_percentage), ref fdiscount_percentage, value); }
        }
        DateTime fcreated_at;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime created_at
        {
            get { return fcreated_at; }
            set { SetPropertyValue<DateTime>(nameof(created_at), ref fcreated_at, value); }
        }
        DateTime fupdated_at;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime updated_at
        {
            get { return fupdated_at; }
            set { SetPropertyValue<DateTime>(nameof(updated_at), ref fupdated_at, value); }
        }
        [Association(@"Product_CategoriesReferencesProducts"), Aggregated]
        public XPCollection<Product_Categories> Product_Categoriess { get { return GetCollection<Product_Categories>(nameof(Product_Categoriess)); } }
        [Association(@"InventoryReferencesProducts"), Aggregated]
        public XPCollection<Inventory> Inventories { get { return GetCollection<Inventory>(nameof(Inventories)); } }
        [Association(@"Purchase_DetailsReferencesProducts"), Aggregated]
        public XPCollection<Purchase_Details> Purchase_Detailss { get { return GetCollection<Purchase_Details>(nameof(Purchase_Detailss)); } }
        [Association(@"Bill_DetailsReferencesProducts"), Aggregated]
        public XPCollection<Bill_Details> Bill_Detailss { get { return GetCollection<Bill_Details>(nameof(Bill_Detailss)); } }
    }

}
