//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Book.Module.BusinessObjects.book_main
{

    [DefaultProperty("id")]
    public partial class Purchases : DevExpress.Persistent.BaseImpl.BaseObject
    {
        short fid;
        public short id
        {
            get { return fid; }
            set { SetPropertyValue<short>(nameof(id), ref fid, value); }
        }
        Suppliers fsupplier_id;
        [Association(@"PurchasesReferencesSuppliers")]
        public Suppliers supplier_id
        {
            get { return fsupplier_id; }
            set { SetPropertyValue<Suppliers>(nameof(supplier_id), ref fsupplier_id, value); }
        }
        Employees femployee_id;
        [Association(@"PurchasesReferencesEmployees")]
        public Employees employee_id
        {
            get { return femployee_id; }
            set { SetPropertyValue<Employees>(nameof(employee_id), ref femployee_id, value); }
        }
        Warehouse fwarehouse_id;
        [Association(@"PurchasesReferencesWarehouse")]
        public Warehouse warehouse_id
        {
            get { return fwarehouse_id; }
            set { SetPropertyValue<Warehouse>(nameof(warehouse_id), ref fwarehouse_id, value); }
        }
        DateTime foccur_date;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime occur_date
        {
            get { return foccur_date; }
            set { SetPropertyValue<DateTime>(nameof(occur_date), ref foccur_date, value); }
        }
        double ftotal_money;
        public double total_money
        {
            get { return ftotal_money; }
            set { SetPropertyValue<double>(nameof(total_money), ref ftotal_money, value); }
        }
        DateTime fcreated_at;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime created_at
        {
            get { return fcreated_at; }
            set { SetPropertyValue<DateTime>(nameof(created_at), ref fcreated_at, value); }
        }
        DateTime fupdated_at;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime updated_at
        {
            get { return fupdated_at; }
            set { SetPropertyValue<DateTime>(nameof(updated_at), ref fupdated_at, value); }
        }
        [Association(@"Purchase_DetailsReferencesPurchases"), Aggregated]
        public XPCollection<Purchase_Details> Purchase_Detailss { get { return GetCollection<Purchase_Details>(nameof(Purchase_Detailss)); } }
        [Association(@"Debt_ReportsReferencesPurchases"), Aggregated]
        public XPCollection<Debt_Reports> Debt_Reportss { get { return GetCollection<Debt_Reports>(nameof(Debt_Reportss)); } }
    }

}
