//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Book.Module.BusinessObjects.book_main
{

    [DefaultProperty("id")]
    public partial class Value_Added_Tax_Bills : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fid;
        public string id
        {
            get { return fid; }
            set { SetPropertyValue<string>(nameof(id), ref fid, value); }
        }
        string fbill_id;
        public string bill_id
        {
            get { return fbill_id; }
            set { SetPropertyValue<string>(nameof(bill_id), ref fbill_id, value); }
        }
        double frate;
        public double rate
        {
            get { return frate; }
            set { SetPropertyValue<double>(nameof(rate), ref frate, value); }
        }
        string fcurrency_unit;
        public string currency_unit
        {
            get { return fcurrency_unit; }
            set { SetPropertyValue<string>(nameof(currency_unit), ref fcurrency_unit, value); }
        }
        string fpayment_method;
        public string payment_method
        {
            get { return fpayment_method; }
            set { SetPropertyValue<string>(nameof(payment_method), ref fpayment_method, value); }
        }
        double ftotal_money_with_tax;
        public double total_money_with_tax
        {
            get { return ftotal_money_with_tax; }
            set { SetPropertyValue<double>(nameof(total_money_with_tax), ref ftotal_money_with_tax, value); }
        }
    }

}
